#!/bin/bash
filename="$(date +\%Y-\%m-\%d)-$(date +\%H-\%M-\%S).png"
filedir="${HOME}/Documents/org/assets/images/"
filepath="${filedir}${filename}"

if [[ ! -d ${filedir} ]]; then
    mkdir -p ${filedir}
fi

flameshot gui -p /tmp -r > ${filepath}
# add border to screenshot
convert -border 2 -bordercolor black ${filepath} ${filepath}

echo "[[${filepath}]]" | xclip -sel clipboard
