#!/bin/bash
xset r rate 200 30
setxkbmap -option shift:both_capslock
setxkbmap -option caps:escape
xmodmap -e "keycode 67 = F15"
xmodmap -e "keycode 68 = F16"
xmodmap -e "keycode 69 = F17"
xmodmap -e "keycode 70 = F18"
