#!/bin/zsh

### Monitors ###
monitors=($(xrandr --listactivemonitors  | awk '{print $4}'))
num_monitors=${#monitors[@]}
display_mode=$(mons | awk 'NR==2 {print $2}')

if [[ $num_monitors -gt 1 ]]; then
    if [[ $display_mode = "extend" ]]; then
        bspc monitor $monitors[1] -d 1;
        bspc monitor $monitors[2] -d 2 3 4 5 6 7 8 9 10;
    else
        bspc monitor $monitors[$num_monitors] -d 1 2 3 4 5 6 7 8 9 10;
    fi
else
    bspc monitor $monitors[1] -d 1 2 3 4 5 6 7 8 9 10;
fi

bspc desktop -f 1
### Gaps ###
bspc config border_width         3
bspc config window_gap           5


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### BSPWM coloring ###

bspc config normal_border_color		"#282c34"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5fafaf"
bspc config presel_feedback_color	"#5fafaf"
bspc config urgent_border_color 	"#dd2727"

### Rules ###
# bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off


### Floating Applications ###
# use xprop then look at the `WM_String` field
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gitk state=floating follow=on
bspc rule -a Nm-connection-editor state=floating follow=on
bspc rule -a Pavucontrol state=floating follow=on
bspc rule -a Timeshift-gtk state=floating follow=on
bspc rule -a Emacs state=tiled



### autostart ###
# need to place here otherwise polybar gets buggy
$XDG_CONFIG_HOME/bspwm/autostart.sh

