#!/bin/sh

### Monitors ###
bspc monitor HDMI-1-2 -d 1 2 3 4 5 6 7 8 9 10
bspc monitor eDP-1-1 -d 1 2 3 4 5 6 7 8 9 10


### Gaps ###
bspc config border_width         3
bspc config window_gap          12


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

### BSPWM coloring ###

bspc config normal_border_color		"#282c34"
bspc config active_border_color		"#1e1e1e"
bspc config focused_border_color	"#5fafaf"
bspc config presel_feedback_color	"#5fafaf"
bspc config urgent_border_color 	"#dd2727"

### Rules ###
bspc rule -a Chromium desktop='^2'
bspc rule -a Screenkey manage=off


### Floating Applications ###
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gitk state=floating follow=on



### autostart ###
# need to place here otherwise polybar gets buggy
$XDG_CONFIG_HOME/bspwm/autostart.sh
