#!/usr/bin/env bash

set -o pipefail
set -o nounset
set -o errexit

script_directory=\$(cd "\$(dirname "\${BASH_SOURCE[0]}")" && pwd -P)
# shellcheck disable=SC2034
project_root=\$(cd "\$(dirname "\${script_directory}")" && pwd -P)

$0
