theme = "gruvbox-dark"
[icons]
name = "awesome"
[icons.overrides]
uptime=""

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R" 

[[block]]
block = "net"
device = "wlp2s0"
ssid = true
speed_up = false
speed_down = false

[[block]]
block = "xrandr"
icons = true
step_width = 1
interval = 1

[[block]]
block = "sound"
step_width = 3

[[block]]
block = "temperature"
collapsed = false
interval = 5
format = "{average}°"
chip = "*-isa-*"

[[block]]
block = "nvidia_gpu"
label = "GTX 960"
show_memory = false
show_clocks = true
interval = 1

[[block]]
block = "cpu"
interval = 0.7

[[block]]
block = "memory"
interval = 5
info_type = "memory"
format_mem = "{Mup}% {SUp}%"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "disk_space"
path = "/home/ukeithu"
alias = "~"
info_type = "available"
unit = "GB"
interval = 20

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "custom"
interval = 999999
command = "echo '\uF011'"
on_click = "i3-nagbar -t warning -m 'What do you want to do?' -b 'Shutdown' 'shutdown now' -b 'Hibernate' 'systemctl hibernate' -b 'Reboot' 'reboot'"

[[block]]
block = "uptime"


