#!/bin/bash
filename="$(date +\%Y-\%m-\%d)-$(date +\%H-\%M-\%S).png"
filepath="${HOME}/vimwiki/assets/images/temp/${filename}"
flameshot gui -p /tmp -r > ${filepath}
# add border to screenshot
convert -border 2 -bordercolor black ${filepath} ${filepath}
echo "<img src='/assets/images/temp/${filename}'/>" | xclip -sel clipboard
