#!/bin/bash
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
rm google-chrome-stable_current_amd64.deb

sudo apt install -y vim i3 kdiff3 xclip git gitk wget curl make build-essential \
libssl-dev

sudo apt install -y python3-pip

pip3 install --user pipenv
pip3 install virtualenv
pip3 install virtualenvwrapper

git clone https://github.com/pyenv/pyenv.git ~/.pyenv

#dependencies for postman
sudo apt install -y libgconf2-4
wget https://dl.pstmn.io/download/latest/linux64 -O postman.tar.gz
sudo tar -xzf postman.tar.gz -C /opt
rm postman.tar.gz
sudo ln -s /opt/Postman/Postman /usr/bin/postman

# volume manager
sudo apt install -y pavucontrol

# Packages for i3

# Replace for dmenu
sudo apt install -y rofi



apt install -y feh xautolock
# install font
apd install fonts-font-awesome libdbus-1-dev fonts powerline

git clone https://github.com/greshake/i3status-rust
cd i3status-rust && cargo build --release

mkdir $HOME/bin
cp target/release/i3status-rs ~/bin/i3status-rs

# clean up
rm -r i3status-rust

