#!/bin/bash
# $1: node id
# Usage: use to resize the `$node_id` window

current_node_id=$(bspc query -N -n "focused")
left_offset=10
right_offset=${left_offset}
top_offset=50
bottom_offset=20

dimensions=$(xdpyinfo | awk '/dimensions/{print $2}')
IFS='x' read -ra dimensions <<< "$dimensions"
window_width=${dimensions[0]}
window_height=${dimensions[1]}

xdotool windowsize "$current_node_id" $(( ("$window_width" / 2 - "$left_offset" - "$right_offset") )) $(( "$window_height" - "$top_offset" - "$bottom_offset"))

case "$1" in
    "left" )
        xdotool windowmove "$current_node_id" "${left_offset}" "${top_offset}"
        ;;
    "right" )
        xdotool windowmove "$current_node_id" $(( "$window_width" / 2 )) "${top_offset}"
        ;;
esac
