#!/bin/sh
id=$(xdo id -n dropdown-terminal);
if [ -z "$id" ]; then
    konsole --name dropdown-terminal &

    # wait for konsole to start, and change it to floating mode immediately
    sleep 0.5
    id=$(xdo id -n dropdown-terminal);
    # sticky will make node stay on screen when workspace is changed
    # locked will prevent node from being closed by `bspc node -c`
    bspc node $id --flag sticky --flag locked --state floating -f
else
    bspc node $id --flag hidden -f
fi

